### ISSUE TITLE
Upload greater than 500 events ran into "events size must be between 1 and 500" error response.

### ISSUE THREAD

**Issue by yoshimasaki** [treasure-data/td-ios-sdk#113]
Hello!
Thank you for convenient SDK for use Treasure Data on iOS.

I recently upgraded to v1.0.0 SDK and ran into the "events size must be between 1 and 500" error response.

I read SDK document and that says bellow and I follow upload events on "When closing the application".

[Upload buffered events to TreasureData](https://github.com/treasure-data/td-ios-sdk#upload-buffered-events-to-treasuredata)

> It depends on the characteristic of your application when to upload and how often to upload buffered events. But we recommend the followings at least as good timings to upload.
> 
> When the current screen is closing or moving to background
> When closing the application

Is there any kind of event restriction?

### env
Xcode: 14.1
iOS: 15.5 simulator - iPhone 7 Plus
Treasure Data SDK version: 1.0.0

### error
![proxyman_error](https://github.com/treasure-data/td-ios-sdk/assets/52738915/801a38e4-6ac6-41d6-bd49-f1ce03cbd9e8)

### reproduce steps
1. log greater than 500 events
2. close app and upload events in background
3. "events size must be between 1 and 500" error response

Thank you for your support😄

**Comment by imnutz** [comment]
This is fixed in v1.0.1
