### ISSUE TITLE
Can not know initialize Success or Failure

### ISSUE THREAD

**Issue by ghost** [treasure-data/td-ios-sdk#120]
Hello!

I recently integrate  SDK and I'm using   v1.0.1 and ran into the "missing parameter:" error response when i upload event

I read SDK document 

env
Xcode: 14.3.1
iOS: 16.4 simulator - iPhone 14 plus
Treasure Data SDK version: 1.0.1

error
`error. errorCode= server_response, message= Optional("Response code was NOT 200. It was: 400")`

reproduce steps
I just integrate code
```
TreasureData.enableLogging()
        TreasureData.initializeEncryptionKey("hello world")
        TreasureData.initialize(withApiKey: apiKey, apiEndpoint: endpoint)
        TreasureData.sharedInstance().defaultDatabase = "testdb"
        TreasureData.sharedInstance().enableAutoAppendUniqId()
        TreasureData.sharedInstance().enableAutoAppendModelInformation()
        TreasureData.sharedInstance().disableRetryUploading()
        TreasureData.sharedInstance().startSession("demotbl")
        TreasureData.sharedInstance().enableAppLifecycleEvent()
```
it dont let me know i .initialize success or not. 

and when i up load event like this 
```
 debugPrint("===== [Analytic] Treasure analytics upload event =====")
        TreasureData.sharedInstance().endSession("demotbl")
        let application = UIApplication.shared
        var bgTask : UIBackgroundTaskIdentifier = UIBackgroundTaskIdentifier(rawValue: 0)
        bgTask = application.beginBackgroundTask(expirationHandler: {
            application.endBackgroundTask(bgTask)
            bgTask = UIBackgroundTaskIdentifier.invalid
        })
        TreasureData.sharedInstance().uploadEvents(callback: {
            application.endBackgroundTask(bgTask)
            bgTask = UIBackgroundTaskIdentifier.invalid
            debugPrint("===== [Analytic] Treasure analytics upload event success =====")
        },
                                onError: {(errorCode, message) -> Void in
            print("===== [Analytic] Treasure analytics upload events: error. errorCode= \(errorCode), message= \(message)")
            application.endBackgroundTask(bgTask)
            bgTask = UIBackgroundTaskIdentifier.invalid
        })
```
I meet error `error. errorCode= server_response, message= Optional("Response code was NOT 200. It was: 400")
`
![Screenshot 2023-11-30 at 17 53 52](https://github.com/treasure-data/td-ios-sdk/assets/118329263/12e07f5b-21e4-451d-9008-0a2283512d84)

Note: Currently I just have endpoint and api key. So I can't access to dashboard to check other info 

Thank you for your support😄

**Comment by tung-vu-td** [comment]
@vienvuyum Please make sure you're using correct endpoint. For tokyo region it is `https://ap01.records.in.treasuredata.com`

**Comment by toru-takahashi** [comment]
no response for a while. close
