### ISSUE TITLE
Privacy Manifest missing Required Reasons API declarations

### ISSUE THREAD

**Issue by StuWebstMW** [treasure-data/td-ios-sdk#123]
Hello, it looks like the current Privacy Manifest includes data use (NSPrivacyCollectedDataTypes), but not any Required Reasons API declarations (NSPrivacyAccessedAPITypes).

Based on a very quick look ([search](https://github.com/search?q=repo%3Atreasure-data%2Ftd-ios-sdk%20NSUserDefaults&type=code)), I was expecting to see at least one entry for NSPrivacyAccessedAPICategoryUserDefaults. I have not checked for any of the other Required Reasons APIs.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

**Comment by tung-vu-td** [comment]
Thank you @StuWebstMW for letting use know!

We will add NSPrivacyAccessedAPICategoryUserDefaults to our manifest soon!

**Comment by tung-vu-td** [comment]
Newly release version now has NSPrivacyAccessedAPICategoryUserDefaults in privacy manifest: https://github.com/treasure-data/td-ios-sdk/releases/tag/1.1.1
