### ISSUE TITLE
Exact version of GZIP dependency not specified

### ISSUE THREAD

**Issue by patrickcapadmi** [treasure-data/td-ios-sdk#124]
The GZIP dependency, included [here](https://github.com/treasure-data/td-ios-sdk/blob/master/Package.swift#L18) is specified as `.upToNextMajor(from: "1.3.1")`

There has been a new release of that SDK in the past few days which will be included automatically without any chance to test or roll back the change.

Expect that dependencies are specified with `exact(...)` such that known exact versions are always used.

**Comment by tung-vu-td** [comment]
Latest release now use exact for GZIP with `1.3.2` version https://github.com/treasure-data/td-ios-sdk/releases/tag/1.1.1.

Thanks for creating the issue!
