### ISSUE TITLE
Add Privacy Manifest to KeenClientTD

### ISSUE THREAD

**Issue by tetsu888** [treasure-data/td-ios-sdk#125]
Hello. After investigating, it seems that KeenClientTD does not have the following required reason API declaration (NSPrivacyAccessedAPITypes).

【NSPrivacyAccessedAPIType】
・NSPrivacyAccessedAPICategoryFileTimestamp
・NSPrivacyAccessedAPICategoryDiskSpace
・NSPrivacyAccessedAPICategoryUserDefaults

KeenClientTD：4.1.0

User defaults APIs
https://github.com/search?q=repo%3Atreasure-data%2FKeenClient-iOS%20%20NSUserDefaults&type=code

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

**Comment by tung-vu-td** [comment]
Thank you very much for letting us know @tetsu888!

We will add NSPrivacyAccessedAPICategoryUserDefaults soon for td-ios-sdk.

Although I'm not sure about two other usages (NSPrivacyAccessedAPICategoryFileTimestamp & NSPrivacyAccessedAPICategoryDiskSpace). I cannot find any instance where we use those APIs in td-ios-sdk or KeenClientTD. Much appreciate if you can point out where the usages occur for us!

**Comment by tetakagi** [comment]
@tung-vu-td 
Thank you for your reply.

We will send you a screenshot of the search results on Xcode.
Please check it out.

NSPrivacyAccessedAPICategoryFileTimestamp
<img width="1204" alt="NSPrivacyAccessedAPICategoryFileTimestamp" src="https://github.com/treasure-data/td-ios-sdk/assets/83123023/7d06f21e-fc5e-4b7d-9c45-0995ec21d74b">

NSPrivacyAccessedAPICategoryDiskSpace
<img width="1204" alt="NSPrivacyAccessedAPICategoryFileTimestamp" src="https://github.com/treasure-data/td-ios-sdk/assets/83123023/554cffdb-3132-42b4-b7c3-f2b0fb26929b">

**Comment by tung-vu-td** [comment]
@tetsu888  Thank you very much <3 We will add NSPrivacyAccessedAPICategoryFileTimestamp & NSPrivacyAccessedAPICategoryDiskSpace as well to privacy manifest.

**Comment by tetsu888** [comment]
@tung-vu-td 
Thank you for your reply.

We will send you a screenshot of the search results on Xcode.
Please check it out.

NSPrivacyAccessedAPICategoryFileTimestamp
<img width="1204" alt="NSPrivacyAccessedAPICategoryFileTimestamp" src="https://github.com/treasure-data/td-ios-sdk/assets/83123023/7d06f21e-fc5e-4b7d-9c45-0995ec21d74b">

NSPrivacyAccessedAPICategoryDiskSpace
<img width="1114" alt="NSPrivacyAccessedAPICategoryDiskSpace" src="https://github.com/treasure-data/td-ios-sdk/assets/83123023/82c23e1c-1276-44dc-91eb-de363660e604">

**Comment by tung-vu-td** [comment]
@tetsu888 New version is released with updated privacy manifest https://github.com/treasure-data/td-ios-sdk/releases/tag/1.1.1. Thank you for all the support 🚀
