### ISSUE TITLE
Update KeenClientTD to remove Xcode warnings

### ISSUE THREAD

**Issue by kobluewater** [treasure-data/td-ios-sdk#2]
The current version of KeenClient is quite old and creating a lot of build warnings.
Could you please update it to newer version?

![image](https://cloud.githubusercontent.com/assets/5379361/7721062/cbf76524-ff0e-11e4-9b93-0e76e4785e9b.png)

**Comment by komamitsu** [comment]
Sorry for our late reply. We resolved those warnings in 0.1.8.
