### ISSUE TITLE
リトライ中にuploadEventsが呼ばれるとRequestが複数発生してしまう

### ISSUE THREAD

**Issue by jsprpr** [treasure-data/td-ios-sdk#30]
https://github.com/treasure-data/td-ios-sdk/blob/master/TreasureData/TDClient.m#L92-L94
ユーザーはデータを複数送信することを期待していないため、
リトライ中にuploadEventsが呼ばれた場合、既存のdataTaskをキャンセルするか、リトライカウントをリセットすることが望ましいです。

**Comment by ryutaroy** [comment]
@m-matsumoto フィードバックありがとうございます、トレジャーデータ矢田です。
弊社側のSDKリクエスト受付サーバ側で、重複排除の仕組みは提供させていただいているのですが、
今回のご指摘は、実際にリトライにより、リクエストが複数行われるのを確認したのか、実際にTD側に重複データが格納されたのを確認したか、でいうとどちらになりますでしょうか？

**Comment by m-matsumoto** [comment]
@ryutaroy 前者です。重複レコードが発生しているため調査している際にこのリトライを見つけたのですが、
このリトライが重複レコードの原因となっているかどうかはまだ確認できていません。

**Comment by toru-takahashi** [comment]
@m-matsumoto サポートの高橋です。
現在、弊社側のバックエンドサーバでは(Mobile/JS SDK)経由のインポートに関して、1時間の重複排除期間を設けています。しかし、SDK側で何度かリトライをしそれでも失敗した場合には、次のアプリ起動時などにそのバッファのアップロードをトライします。
この間隔が、1時間を超えてしまうとデータの重複が発生してしまう可能性はございます。

下記のパラメータを有効にしていただくことでレコード毎にUUIDの生成も可能性ですので、インポート後にSQLで重複排除を行うことも可能ですので、こちらのご利用を検討頂けますと幸いです。
https://github.com/treasure-data/td-ios-sdk#adding-an-uuid-to-each-event-record-automatically

**Comment by m-matsumoto** [comment]
@toru-takahashi ご案内ありがとうございます。検討してみます。

**Comment by huylenq** [comment]
@jsprpr I guess it's going alright? I'm gonna close this for now, please feel free to reopen if it's still an issue.
