### ISSUE TITLE
uploadEventで送信するデータがない場合、ハンドラーが呼ばれない

### ISSUE THREAD

**Issue by m-matsumoto** [treasure-data/td-ios-sdk#31]
KeenClient.m内の下記でelseの処理がないことに起因しています。
```
        if ([data length] > 0) {
            // then make an http request to the keen server.
            [self sendEvents:data completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                // then parse the http response and deal with it appropriately
                [self handleAPIResponse:response andData:data forEvents:eventIds onSuccess:onSuccess onError:onError];
            }];
        }
```
applicationDidEnterBackgroundでuploadEventを実行する場合、ハンドラーをもとにendBackgroundTaskを実行するため、送信するデータがない場合もハンドリングする口が欲しいです。

**Comment by toru-takahashi** [comment]
こんにちは。サポートの高橋です。
こちら社内にてフィードバックしており、改善しましたらお知らせ致します。
（まだ目処は未定です。）

**Comment by komamitsu** [comment]
@m-matsumoto Thanks for reporting this issue.
We released 0.1.24 to fix the issue. Could you try the new version?

**Comment by m-matsumoto** [comment]
@komamitsu ご対応ありがとうございました。無事endBackgroundTaskできるようになりました。
