### ISSUE TITLE
Xcode archive failed due to version numbers.

### ISSUE THREAD

**Issue by morizotter** [treasure-data/td-ios-sdk#4]
![8edf75b0-8725-11e5-9fc3-d8ce94bab354](https://cloud.githubusercontent.com/assets/536954/11033538/51fcf5f8-8727-11e5-9bdc-5c310b359dd2.jpg)

Xcode archive failed due to version numbers below:

- td-ios-sdk: 3.2.20.1
- KeenClientTD: 0.1.6.1

We avoid this failure to change version number locally, but it's better to change version nuber to *a two-period-separated list of positive integers* written in the guide.

ref: [AppDistributionGuide.pdf](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppDistributionGuide.pdf)

**Comment by komamitsu** [comment]
@morizotter Thanks! I'll take care of that.

**Comment by morizotter** [comment]
:+1:

**Comment by komamitsu** [comment]
@morizotter We released td-ios-sdk:0.1.8 and KeenClientTD:3.2.22.
