### ISSUE TITLE
Recommended version?

### ISSUE THREAD

**Issue by zapjonny** [treasure-data/td-ios-sdk#41]
Your docs specify:

> pod 'TreasureData-iOS-SDK', '= 0.1.24'

So is the recommended version 0.1.24?

The latest version is 0.1.26, is that one unsafe?

**Comment by huylenq** [comment]
I know this is not a super responsive answer but the recommended version now is [0.1.27](https://github.com/treasure-data/td-ios-sdk/releases/tag/0.1.27)

**Comment by huylenq** [comment]
If there're any other concerns, please feel free to re-open this.
