### ISSUE TITLE
Could Treasure Data support adding more detail information to the device model?

### ISSUE THREAD

**Issue by nam-dh** [treasure-data/td-ios-sdk#71]
The doc says:
```
Adding the device model information to each event automatically

It outputs the following column names and values:
td_device : UIDevice.model
td_model : UIDevice.model
```

So both 2 columns `td_device` and `td_model` will have the same value?

`UIDevice.model` outputs model of the device, likes `iPhone`, `iPad`.
Could Treasure Data support adding more detail information to the device model value, like `iPhone X`, `iPad Pro`?

Thank you.

**Comment by toru-takahashi** [comment]
td_device is used for a consistency of column name with Android SDK. Android SDK has such a info. But, UIDevice object doesn't have it.
