### ISSUE TITLE
How to use in Swift framework?

### ISSUE THREAD

**Issue by uny** [treasure-data/td-ios-sdk#8]
This framework is a static library in Objective-C.
When using it in Swift framework, Bridging-Header cannot be used.
So, how to use it in Swift framework?
Availability without cocoapods would be appreciated.

**Comment by komamitsu** [comment]
Sorry for my late reply. I'll check it later.

> Availability without cocoapods would be appreciated.
You don't want to use Carthage as well?

**Comment by uny** [comment]
Carthage is better.
If this framework can be used in Swift Framework, CocoaPods might be acceptable.

**Comment by komamitsu** [comment]
I see. Is this article useful for you? http://qiita.com/morizotter/items/de265031a103b12442ac

**Comment by uny** [comment]
No...
It is the problem subject to using bridging header.
Above Xcode7, we cannot use bridging header when making framework.

**Comment by komamitsu** [comment]
@uny I added an example project (https://github.com/treasure-data/td-ios-sdk/tree/master/TreasureDataExampleSwift) and updated README.md. I hope they can help you.
