### ISSUE TITLE
Feature request: Be able to install via Swift Package Manager

### ISSUE THREAD

**Issue by nacho4d** [treasure-data/td-ios-sdk#95]
Since Xcode11, SPM is the easiest way to install third party libraries. Since Xcode12 also binary frameworks can be distributed via SPM. 

I kindly ask you to consider SPM support in this library :)

**Comment by toru-takahashi** [comment]
Same as well.
https://github.com/treasure-data/td-ios-sdk/issues/96#issuecomment-868196161

**Comment by nacho4d** [comment]
@toru-takahashi 
The main reason I requested SPM is to be able to do Bitcode and I think you already realized this. Thank you. 
I will write more details in #96 

Regarding SPM support: I have done preliminary SPM support in my fork. There is a couple of compiler warnings that might need work but overall it works.  Note: This is a personal voluntary work and **it does not need attribution to my company or not even me.** Feel free to use or not use this code as you decide😀 .  ボランティアとしての貢献です。必要でしたらご自由にどうそ 👍 

Keen-Client:
https://github.com/nacho4d/KeenClient-iOS/commit/c784132ba262009503e693e4a4b3711606c928e5
Treasure-Data-iOS:
https://github.com/nacho4d/td-ios-sdk/commit/ad290fef9eafff274a6733017a01c0077ebcccb3

In both cases minimal changes have been done to source code. I only needed to move non-public classes to another folder so SPM exports the right headers.

**Comment by toru-takahashi** [comment]
@nacho4d 
Hell!

Thank you for your PR - https://github.com/treasure-data/td-ios-sdk/pull/106
We will be ready to release it soon!

If you don't mind, could you fill your address in the following Google form?
We would like to deliver some swag to you as a token of our appreciation. 

- https://forms.gle/37jhNBFJo9kyLvLx9

**Comment by toru-takahashi** [comment]
@nacho4d no problem. Thank you for your efforts.
Sorry, I removed a access restriction. please try it again.

**Comment by nacho4d** [comment]
@toru-takahashi 
Thank you! I gladly accept!

I have filled the form and sent it.

**Comment by toru-takahashi** [comment]
Thank you! we will deliver soon!

**Comment by tung-vu-td** [comment]
Thanks @nacho4d for your contributions 🙇 . I'm happy to let you know that TreasureData iOS SDK version 0.9.0 is now available via SPM!

**Comment by nacho4d** [comment]
WOW!

**Comment by nacho4d** [comment]
I quickly saw the sources. 

The package.resolved fails still points to my repo. I thought you might know :]
https://github.com/treasure-data/td-ios-sdk/blob/c132cd4875ad8eb8f898cb95e96a8d6639f1cc64/Package.resolved#L6

**Comment by tung-vu-td** [comment]
Thanks @nacho4d for catching this. I cleaned up.
