### ISSUE TITLE
Built Framework does not support Bitcode. Cannot be used from Swift

### ISSUE THREAD

**Issue by nacho4d** [treasure-data/td-ios-sdk#96]
- In some projects cocoa pods is not an option and we need to rely in built (xc)frameworks. 
 
So I have downloaded and investigated provided [Framework from README](http://cdn.treasuredata.com/sdk/ios/0.8.0/TreasureData-iOS-SDK.framework.zip)

- It looks like that framework is just 2 static libraries sticked together using libtool. This kind of framework is not usable in new Swift projects. It can only be used from Objective-C.
- It does NOT contain Bitcode which is the default in new Xcode projects.
- Eventhough you providing a real framework and make it universal, in Xcode12 it will lead to warnings. Instead of using libtool or lipo now the recommended way is XCFrameworks.

I kindly ask you to provide a XCFramework with Bitcode support 🙇

**Comment by toru-takahashi** [comment]
Hello,

Thank you for raising a request.
Are you using TreasureData in your company or in any projects?
That would be helpful if you can report this request to support(at)treasure-data.com
So that we can efficiently prioritize your request based on your business situation behind of your request.

Thank you,

**Comment by nacho4d** [comment]
@toru-takahashi 
Sorry it took me several days to reply. 

Yes, this is for a client project. Today I did a request to my client and probably in some days you should receive a communication. 

Kind regards.

**Comment by monolithic-adam** [comment]
@toru-takahashi Any status update on this? We are trying to move away from cocoapods and this SDK has become a blocker for that...
This is for a company that I am contracted with btw.

**Comment by toru-takahashi** [comment]
@monolithic-adam 

Please build the package by the following procedure.

1 - Download https://github.com/treasure-data/td-ios-sdk/tree/master/TreasureDataExampleSwift

2 - Create xcondig into the project

```
TreasureData-iOS-SDK.debug.xcconfig
TreasureData-iOS-SDK.release.xcconfig
KeenClientTD.debug.xcconfig
KeenClientTD.release.xcconfig
```

They should have the following options

```
ENABLE_BITCODE = YES
BITCODE_GENERATION_MODE = bitcode
OTHER_CFLAGS = -fembed-bitcode
BUILD_LIBRARY_FOR_DISTRIBUTION = YES
SKIP_INSTALL = NO
```

3 - Build a release package for simulator and device

4 - Convert .framework to xcframework

```
# framework for KeenClientTD
xcodebuild -create-xcframework \
    -framework Release-iphoneos/KeenClientTD/KeenClientTD.framework \
    -framework Release-iphonesimulator/KeenClientTD/KeenClientTD.framework \
    -output KeenClientTD.xcframework
```


```
# framework for TD iOS SDK
xcodebuild -create-xcframework \
    -framework Release-iphoneos/TreasureData-iOS-SDK/TreasureData_iOS_SDK.framework \
    -framework Release-iphonesimulator/TreasureData-iOS-SDK/TreasureData_iOS_SDK.framework \
    -output TreasureData_iOS_SDK.xcframework
```

4 - Introduce the frameworks to your app

If this doesn't work, please connect with our support. Thank you

**Comment by nacho4d** [comment]
@toru-takahashi 

Yes we can do that. 

Please note that with recent Macs with M1 we need to do the process again so support M1 natively for simulators.

It would be nice if you consider supporting swift package manager.  All the required changes are in these commits.

Keen-Client:
https://github.com/nacho4d/KeenClient-iOS/commit/c784132ba262009503e693e4a4b3711606c928e5
Treasure-Data-iOS:
https://github.com/nacho4d/td-ios-sdk/commit/ad290fef9eafff274a6733017a01c0077ebcccb3

(PS: I didn't make a pull request just because I thought you might prefer not to show my name in the git log but if you are OK with me doing the pull request I can do it)

**Comment by toru-takahashi** [comment]
Thank you.

I'll ask the SDK dev team to take a look at these commits.
Feel free to send PR to our public  repo. It would be helpful for us to review your req.

**Comment by nacho4d** [comment]
Since Xcode14 bitcode support is deprecated. I think this issue is not an issue anymore. IMO this issue can be closed.

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

**Comment by tung-vu-td** [comment]
Thanks @nacho4d for the find!
